<?php
/**
 * iDealBiz
 *
 * WARNING: This file is part of the iDealBiz theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package iDealBiz\Templates
 * @author  WidgiLabs
 * @license GPL-2.0+
 * @link    http://widgilabs.com/
 */


class iDealBizCTA extends \WP_Widget {

	function __construct() {
		parent::__construct(

			// Base ID
			'iDealBiz_cta',

			// Widget name will appear in UI
			__('iDealBiz CTA', 'idealbiz'),

			// Widget description
			array( 'description' => __( 'Call to Action with title, desciption and button', 'idealbiz' ), )
		);
	}

	// Creating widget front-end
	public function widget( $args, $instance ) {
		$title        = apply_filters( 'iDealBizCTA_title', $instance['title'] );
		$description  = apply_filters( 'iDealBizCTA_description', $instance['description'] );
		$button_label = apply_filters( 'iDealBizCTA_button_label', $instance['label'] );
		$button_link  = apply_filters( 'iDealBizCTA_button_link', $instance['link'] );

		// before and after widget arguments are defined by themes
		echo $args['before_widget'];

		///pricing/?action=register&type=service

		if ( ! empty( $button_link ) ) :

		printf('<aside class="service__register-cta service__widget box">
					<div class="title-intro">
						%1$s
					</div>
					<div class="text-intro">
						<p>
							%2$s
						</p>
					</div>
					<a href="%3$s"
					   title="%4$s" class="button">
						%4$s
					</a>
				</aside>',
			$title,
			$description,
			$button_link,
			$button_label
			);

		endif;

		echo $args['after_widget'];
	}

	// Widget Backend
	public function form( $instance ) {

		$title = '';
		if ( isset( $instance[ 'title' ] ) ) {
			$title = $instance[ 'title' ];
		}

		$description = '';
		if ( isset( $instance[ 'description' ] ) ) {
			$description = $instance[ 'description' ];
		}

		$link = false;
		if ( isset( $instance[ 'link' ] ) ) {
			$link = $instance[ 'link' ];
		}

		$label = '';
		if ( isset( $instance[ 'label' ] ) ) {
			$label = $instance[ 'label' ];
		}

		?>
		<p>
			<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:', 'idealbiz' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo esc_attr( $title ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id( 'description' ); ?>"><?php _e( 'Description:', 'idealbiz' ); ?></label>
			<textarea class="widefat" id="<?php echo $this->get_field_id( 'description' ); ?>" name="<?php echo $this->get_field_name( 'description' ); ?>"><?php echo esc_attr( $description ); ?></textarea>
		</p>
		<p>
			<label for="<?php echo $this->get_field_id( 'label' ); ?>"><?php _e( 'Button Label:', 'idealbiz' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id( 'label' ); ?>" name="<?php echo $this->get_field_name( 'label' ); ?>" type="text" value="<?php echo esc_attr( $label ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id( 'link' ); ?>"><?php _e( 'Button Link:', 'idealbiz' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id( 'link' ); ?>" name="<?php echo $this->get_field_name( 'link' ); ?>" type="text" value="<?php echo esc_attr( $link ); ?>" />
		</p>
	<?php
	}

	// Updating widget replacing old instances with new
	public function update( $new_instance, $old_instance ) {

		$instance                = array();
		$instance['title']       = ( ! empty( $new_instance['title'] ) ) ? strip_tags( $new_instance['title'] ) : '';
		$instance['description'] = ( ! empty( $new_instance['description'] ) ) ? strip_tags( $new_instance['description'] ) : '';
		$instance['label']       = ( ! empty( $new_instance['label'] ) ) ? strip_tags( $new_instance['label'] ) : '';
		$instance['link']        = ( ! empty( $new_instance['link'] ) ) ? strip_tags( $new_instance['link'] ) : '';
		return $instance;
	}
} // Class wpb_widget ends here


add_action('widgets_init', create_function('', 'return register_widget("iDealBizCTA");'));
